// <auto-generated />
using System;
using CinemaAPI.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaAPI.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20221209192644_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaAPI.Models.Film", b =>
                {
                    b.Property<Guid>("Id_Film")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Dubbing")
                        .HasColumnType("bit");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is3D")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sub")
                        .HasColumnType("bit");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id_Film");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("CinemaAPI.Models.Location", b =>
                {
                    b.Property<Guid>("id_location")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_location");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.Property<Guid>("id_room")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("column")
                        .HasColumnType("int");

                    b.Property<Guid>("locationid_location")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("row")
                        .HasColumnType("int");

                    b.Property<string>("taken_seats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unavailable_seats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_room");

                    b.HasIndex("locationid_location");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CinemaAPI.Models.Screening", b =>
                {
                    b.Property<Guid>("Screening_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Film")
                        .HasColumnType("int");

                    b.Property<int>("Id_Room")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("filmId_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("roomid_room")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Screening_ID");

                    b.HasIndex("filmId_Film");

                    b.HasIndex("roomid_room");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("CinemaAPI.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Film")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("roomid_room")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("roomid_room");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.HasOne("CinemaAPI.Models.Location", "location")
                        .WithMany("rooms")
                        .HasForeignKey("locationid_location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("CinemaAPI.Models.Screening", b =>
                {
                    b.HasOne("CinemaAPI.Models.Film", "film")
                        .WithMany("Screenings")
                        .HasForeignKey("filmId_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Room", "room")
                        .WithMany("Screenings")
                        .HasForeignKey("roomid_room")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("film");

                    b.Navigation("room");
                });

            modelBuilder.Entity("CinemaAPI.Models.Ticket", b =>
                {
                    b.HasOne("CinemaAPI.Models.Room", "room")
                        .WithMany("Tickets")
                        .HasForeignKey("roomid_room")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("room");
                });

            modelBuilder.Entity("CinemaAPI.Models.Film", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("CinemaAPI.Models.Location", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.Navigation("Screenings");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
